### ISSUE TITLE
It is not detecting slowloris attacks

### ISSUE THREAD

**Issue by arch-user-france1** [PoCFrance/SmartShark#4]
This tool sadly doesn't seem to detect slowloris attacks. Am I missing something?

**Comment by sasindu-dilan** [comment]
> This tool sadly doesn't seem to detect slowloris attacks. Am I missing something?

did you found any way to test it

**Comment by arch-user-france1** [comment]
It isn't meant for this.

**Comment by sasindu-dilan** [comment]
did you found any tool to test this can give me a quick tip

**Comment by arch-user-france1** [comment]
Slowloris attacks are no big deal anymore with current webservers. What webserver are you hosting your application with?

**Comment by sasindu-dilan** [comment]
it just for a project i just hosted apache2 server and tried dos attack but it didn't  work but i try MIM attack it worked not perfectly but it worked .i just need attack on the apache server using dos😥

**Comment by arch-user-france1** [comment]
I don't believe slowloris attacks still work on Apache. If you're unsure, you can use [this tool](https://github.com/gkbrk/slowloris) to test your project. Please refrain from attacking any other services which do not belong to you using this tool.

**Comment by sasindu-dilan** [comment]
i used slowloris  but it not show anything i think it because of the data sets in the smartshark do i need to put all of the data sets mentions in the repository

**Comment by sasindu-dilan** [comment]
anything  means smart shark capture it as a normal packets
